apiVersion: apps/v1
kind: Deployment
metadata:
    name: goserver
spec:
    replicas: 1
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                - name: goserver
                  image: leandromello/projeto-app-k8s:latest
                  imagePullPolicy: Never
                  ports:
                    - containerPort: 3000
